version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 99
  reviewers:
  - dsyncerek
  assignees:
  - dsyncerek
  ignore:
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.3
    - 2.32.4
    - 2.32.8
    - 2.32.9
